name: Terraform

# Quando rodar a pipeline:
on:
  push:
    branches: [ "main" ]      # Quando der push na main
  pull_request:               # Ou quando abrir pull request

# Permissões mínimas
permissions:
  contents: read

jobs:
  terraform:
    name: Rodar Terraform
    runs-on: ubuntu-latest    # Vai rodar numa máquina Ubuntu temporária

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    
      
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6   # Você pode trocar pela versão que quiser

      - name: Iniciar Terraform
        run: terraform init

      - name: Primeiro check
        run: terraform fmt -write=true
        
      - name: Verificar formato dos arquivos
        run: terraform fmt -check

      - name: Validar sintaxe
        run: terraform validate

      - name: Gerar plano
        run: terraform plan

      # ⚠️ Opcional — só se quiser aplicar automaticamente
      # - name: Aplicar mudanças
      #   run: terraform apply -auto-approve
